#ifndef _INSDEF_H_
#define _INSDEF_H_

#define INS_ADC          0
#define INS_ADD          1
#define INS_AND          2
#define INS_BBL          3
#define INS_BIC          4
#define INS_BKPT         5
#define INS_BLX1         6
#define INS_BLX2         7
#define INS_BX           8
#define INS_BXJ          9
#define INS_CDP          10
#define INS_CLZ          11
#define INS_CMN          12
#define INS_CMP          13
#define INS_CPS          14
#define INS_CPY          15
#define INS_EOR          16
#define INS_LDC          17
#define INS_LDM1         18
#define INS_LDM2         19
#define INS_LDM3         20
#define INS_LDR          21
#define INS_LDRB         22
#define INS_LDRBT        23
#define INS_LDRD         24
#define INS_LDREX        25
#define INS_LDRH         26
#define INS_LDRSB        27
#define INS_LDRSH        28
#define INS_LDRT         29
#define INS_MCR          30
#define INS_MCRR         31
#define INS_MLA          32
#define INS_MOV          33
#define INS_MRC          34
#define INS_MRRC         35
#define INS_MRS          36
#define INS_MSR          37
#define INS_MUL          38
#define INS_MVN          39
#define INS_ORR          40
#define INS_PKHBT        41
#define INS_PKHTB        42
#define INS_PLD          43
#define INS_QADD         44
#define INS_QADD16       45
#define INS_QADD8        46
#define INS_QADDSUBX     47
#define INS_QDADD        48
#define INS_QDSUB        49
#define INS_QSUB         50
#define INS_QSUB16       51
#define INS_QSUB8        52
#define INS_QSUBADDX     53
#define INS_REV          54
#define INS_REV16        55
#define INS_REVSH        56
#define INS_RFE          57
#define INS_RSB          58
#define INS_RSC          59
#define INS_SADD16       60
#define INS_SADD8        61
#define INS_SADDSUBX     62
#define INS_SBC          63
#define INS_SEL          64
#define INS_SETEND       65
#define INS_SHADD16      66
#define INS_SHADD8       67
#define INS_SHADDSUBX    68
#define INS_SHSUB16      69
#define INS_SHSUB8       70
#define INS_SHSUBADDX    71
#define INS_SMLAXY       72
#define INS_SMLAD        73
#define INS_SMLAL        74
#define INS_SMLALXY      75
#define INS_SMLALD       76
#define INS_SMLAWY       77
#define INS_SMLSD        78
#define INS_SMLSLD       79
#define INS_SMMLA        80
#define INS_SMMLS        81
#define INS_SMMUL        82
#define INS_SMUAD        83
#define INS_SMULXY       84
#define INS_SMULL        85
#define INS_SMULWY       86
#define INS_SMUSD        87
#define INS_SRS          88
#define INS_SSAT         89
#define INS_SSAT16       90
#define INS_SSUB16       91
#define INS_SSUB8        92
#define INS_SSUBADDX     93
#define INS_STC          94
#define INS_STM1         95
#define INS_STM2         96
#define INS_STR          97
#define INS_STRB         98
#define INS_STRBT        99
#define INS_STRD         100
#define INS_STREX        101
#define INS_STRH         102
#define INS_STRT         103
#define INS_SUB          104
#define INS_SWI          105
#define INS_SWP          106
#define INS_SWPB         107
#define INS_SXTAB        108
#define INS_SXTAB16      109
#define INS_SXTAH        110
#define INS_SXTB         111
#define INS_SXTB16       112
#define INS_SXTH         113
#define INS_TEQ          114
#define INS_TST          115
#define INS_UADD16       116
#define INS_UADD8        117
#define INS_UADDSUBX     118
#define INS_UHADD16      119
#define INS_UHADD8       120
#define INS_UHADDSUBX    121
#define INS_UHSUB16      122
#define INS_UHSUB8       123
#define INS_UHSUBADDX    124
#define INS_UMAAL        125
#define INS_UMLAL        126
#define INS_UMULL        127
#define INS_UQADD16      128
#define INS_UQADD8       129
#define INS_UQADDSUBX    130
#define INS_UQSUB16      131
#define INS_UQSUB8       132
#define INS_UQSUBADDX    133
#define INS_USAD8        134
#define INS_USADA8       135
#define INS_USAT         136
#define INS_USAT16       137
#define INS_USUB16       138
#define INS_USUB8        139
#define INS_USUBADDX     140
#define INS_UXTAB        141
#define INS_UXTAB16      142
#define INS_UXTAH        143
#define INS_UXTB         144
#define INS_UXTB16       145
#define INS_UXTH         146



#endif
